# Generated by Django 6.0.3 on 2026-05-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_producto_status_alter_producto_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='sucursales/'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
