# Generated by Django 6.0.3 on 2026-05-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_sucursal_imagen_sucursal_status_sucursal_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='tipo',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='direccion',
            field=models.TextField(default='sin direccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sucursal',
            name='ubicacion_mapa',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='ciudad',
            field=models.CharField(default='sin ciudad', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='estado',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
